#!/usr/bin/env python

import requests
import sys

def search(ip):
    r = requests.get("http://freeapi.ipip.net/%s" % (ip,))
    return r.json()

if __name__ == '__main__':
    if len(sys.argv) == 1:
        print "Usage: ip [$ip] [$ip1]"
        sys.exit()
    for ip in sys.argv[1:]:
        print ":".join(search(ip))
